### ISSUE TITLE
UI configurability

### ISSUE THREAD

**Issue by halxinate** [moezbhatti/qksms#1018]
I see folks complaining about UI features removed. Just make everybody happy - make that configurable too.

**Comment by moezbhatti** [comment]
Most of the features that were removed had less than 0.5% of users actually using them. Sure, you can add more and more options and make everyone happy, but a line needs to be drawn otherwise the app will become incredibly cluttered and hard to navigate. In QKSMS 2.7.3 it was already rather difficult to navigate and find the options that were truly important, because they were drowned out by things that hardly anyone needed or used.

**Comment by halxinate** [comment]
Your anlythics could be wrong. I used the permanent night mode just once in
several months, but that doesn't mean I don't need it.
