### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by GrPK** [moezbhatti/qksms#1044]
Hello! Great app, really love it! I have a few suggestion to make it even better:
1. Option to delete multiple messages at once.
2. When selecting QK Reply, the heads-up should not show up as well.
3. When selecting QK Reply, should be an option to make it appear from pressing the heads-up notification, not automatically, so that you dont have to enter the application.
4. Selecting the colour of a conversation should change the bubble with the letter as well.
5. (Optional, but eager to see) Option to set different patterns of vibration (maybe for different contacts).
6. A wake-up screen option (for phones that dont have such a feature).
Thank you for your work and soon I'll buy + edition, but I really hope that at least 1,2,3 will be part of the app.

**Comment by realmain** [comment]
1. #874

3. #388

**Comment by MyNameIsCosmo** [comment]
These should be in separate issues.
@GrPK - You should split your suggestions into separate issues, with the duplicates (#42 and #388) omitted as per [realmain's post](#issuecomment-381436558), then close this issue.

**Comment by zawyer1** [comment]
Regarding your 3rd point, the good thing about QK Reply is that it automatically appears when you unlock the phone. No other app has this. However, I see your point about having an option so that the QK Reply window appears only when you click the head-up notification, that sounds a bit neat, although I wouldn't personally use it.

**Comment by moezbhatti** [comment]
2 - #1046
3 - #1047
6 - #1048
