### ISSUE TITLE
QK Reply crashes on certain devices

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#1054]
This is because of the line `notification.setCustomHeadsUpContentView(RemoteViews(Parcel.obtain()))`

**Comment by Mrfiregem** [comment]
It seems trying to fix this bug for others broke it for me. Before the update, QK message popped up whenever it needed to just fine, but after the most recent update I get a message saying QK crashes in the background and when I open the app, sure enough there is a new message.

This is on the LG k20 Plus (lgmp260) running Android 7 that came with the device.

**Comment by moezbhatti** [comment]
Can you open up the QKSMS settings and check which version of the app you're running?

**Comment by Mrfiregem** [comment]
Sorry, it turns out I was still on 3.0.6 but thought I was on 3.0.7 due to the update on F-Droid yesterday. Turns out F-Droid is one version behind GitHub releases. I went to check my version right after posting to make sure, but didn't think you'd reply before I deleted my complaint. Sorry to bother, thanks for the support, though 👍

**Comment by moezbhatti** [comment]
@Mrfiregem no problem, glad it's working for you!
