### ISSUE TITLE
Merge conversations with same Contact

### ISSUE THREAD

**Issue by KruziikG** [moezbhatti/qksms#1210]
### DESCRIPTION
Display not correct when you receive message from a contact who has two numbers. qksms will show the old conversation . Like this:
![91125a39-6405-47ef-b4ce-1cd218e4c728](https://user-images.githubusercontent.com/11470789/41757205-269d738c-7613-11e8-991b-42abf3cf1920.gif)

### STEPS
1. create a contact with 2 phone numbers.
2. have a conversation whit number A,
3.To see more clearly, you can make this conversation not in the first screen
4. have a conversation whit number B,

### EXPECTED
When receive from number B, QKSMS should display a new conversation.

### OBSERVATIONS
QKSMS  jump to the former conversation

**Comment by ADepic** [comment]
I disagree. I think it should stay as one conversation because it is one contact...

I think best solution for this is to have a option in the settings to go to your solution .

**Comment by moezbhatti** [comment]
At least for now, this is the correct behavior, to have a separate conversation for each phone number of a contact.

The reason for this is because of a technical limitation where the Android SMS database has a field in conversations that has a list of all the phone numbers associated with the conversation. It's there's one number, it's expected that it's a 1:1 conversation and messages should be sent as normal SMS. And when there's multiple numbers, it's expected that it's a group conversation and messages should be sent as group MMS.

This isn't to say that it's impossible to have 1:1 conversations that have multiple numbers associated with them, but it's tricky to solve because QKSMS needs to ensure that it stays compatible with other SMS apps that are reading from the Android SMS database, and will require changing how some significant portions of the app function
