### ISSUE TITLE
Incorrect date formats for English (Australia)

### ISSUE THREAD

**Issue by gkomarnicki** [moezbhatti/qksms#1240]
I'm using English (Australia) and in QKSMS, the dates in conversation threads are in mmm. d format and when viewing message info, it's m/d/yyyy. I think it should be d mmm. (3 Jul., not Jul. 3) and d/m/yyyy, respectively, though (d)d/mm/yyyy is the written date format in Australia.

**Comment by deu13434** [comment]
The problem is that the DateFormatter class is using hardcoded patterns.

Similar to #1090, Android provides ways to format a date based on the device settings:
https://developer.android.com/reference/java/text/DateFormat
Using FieldPosition it should also be possible to remove part of the String, just like the current patterns do.

The same problem applies to the conversations overview.
