### ISSUE TITLE
Have to increase MMS compression after last couple updates

### ISSUE THREAD

**Issue by JPDVM2014** [moezbhatti/qksms#1287]
When I first started using QKSMS, I was able to send MMS using the 2,000kb option. However, the last couple updates, I have had to lower it to get anything to go through. I'm currently at 600kb.

I thought maybe it was T-Mobile, but my backup SMS app, Textra, has no issues sending MMS with no size limit set.

**Comment by moezbhatti** [comment]
This is to be expected. Previously, QKSMS was compressing the images far below the limit that was set, allowing you to pick a higher setting and have the messages still send successfully.

I recently improved the image compression so that it compresses the image to be very close to the set size, meaning settings that may have worked previously will not work anymore.

---

As for Textra working with no size limit set, I think that the setting may be a little bit misleading in Textra, but I'd like you confirm for me in case I'm only experiencing this on my own phone.

For me what happens is that when I sent an image with Textra, if I look at the message details, it shows the original size of the file. So, everything looks good.

However, what I noticed is that if I send an image to myself, the _outgoing_ message shows the original image size, but the image that I actually receive is much much smaller. So it looks like behind the scenes, Textra is compressing the images much further than what the setting describes.

Could you test this on your own phone and verify whether or not this happens to you as well?

**Comment by JPDVM2014** [comment]
It does do that in Textra for me too! Thanks for responding! I just thought I was having to make my MMS worse and worse. Glad to know that isn't the case.

**Comment by moezbhatti** [comment]
Thank you for confirming!

And nope - if anything, quality should be better now :)
