### ISSUE TITLE
Database re-sync deleted messages

### ISSUE THREAD

**Issue by sccal** [moezbhatti/qksms#1302]
Hello,
I mistakenly deleted an entire thread on Textra which deleted from android sms as well. The messages are still in QKSMS. If I re-sync will those messages be deleted?

If so, is there anyway to save these messages and re-import them into the main database?

**Comment by Leroux47** [comment]
Hello sccal,

Which version of QKSMS are you using ? Is it the Play Store or F-Droid version (the app is entirely free when you get it from F-Droid) ? Since the v3.5 it is possible to backup your messages. If you could do it, I think you can import that backup later, after re-syncing the Android sms DB.
