### ISSUE TITLE
Why doesent qksms use the com.android.providers.blockednumber database, and contribute to it?

### ISSUE THREAD

**Issue by ashjas** [moezbhatti/qksms#1304]
### DESCRIPTION
QKSMS does not use data already present in android OS provider: com.android.providers.blockednumber
This already has thousands of numbers ive been blocking for a while from android messages.
So all that information cant be reused?
And the blocking in qksms should only add to this provider, as this is device global database, so that this important database can be reused.

### EXPECTED
QKSMS should use data from com.android.providers.blockednumber and append while blocking from the app.

### OBSERVATIONS
QKSMS seems to be using its own database for blocking.

**Comment by moezbhatti** [comment]
Awesome, I didn't know this existed. Thanks for the heads up!

**Comment by neekless** [comment]
Is this working? Because it's not happening on my device. Blocked numbers are not added to the device database.

**Comment by moezbhatti** [comment]
Those changes haven't been released yet. Though after some further testing, I've decided to hold off on releasing them until I can spend some time and scope out this feature further. The reason being is that I've added the ability to integrate with a few other blocking managers, as well as added the ability to choose what happens when you receive a message from a blocked number. 

You can set the app to either drop the message immediately, or silently receive it and just hide it in the blocking section for you to review later. I thought that the android blocked number database would be compatible with this and would allow me to just use it as a database and handle the blocking myself, but it turns out this is not the case, and messages from numbers added to that database will never be received by QKSMS, breaking the ability to review the messages later

**Comment by moezbhatti** [comment]
Closing this issue

Maintaining a separate block list in QKSMS allows us to make blocking more powerful, by allowing the user to choose whether or not they want to keep the blocked messages. The global blocklist simply doesn't allow us to do this, since messages from one of the numbers blocked there will never even make it to the SMS app

The global blocklist will still be respected, so I don't think it's a problem if we're not contributing new entries to that list
