### ISSUE TITLE
SMS text body in URI is not retrieved by QKSMS.

### ISSUE THREAD

**Issue by AntoineVe** [moezbhatti/qksms#1321]
### DESCRIPTION

SMS URI (as described in the RFC 5724) are like sms:+0000000?body=Hello
When clicking on those URI, QKSMS doesn't retrieve the body, but the android SMS app does.

**Comment by moezbhatti** [comment]
Related to a86229db524c5cecf8f3f733e472e7e0e15ee661

**Comment by Roy-Orbison** [comment]
It should probably also handle the `sms:+0000000&body=Hello` format that Apple uses, and some developers don't realise isn't standard.

**Comment by moezbhatti** [comment]
That one is a bit tricker to support. I think most developers forget to support it because when an intent is received with multiple params, android will split them up for you and tell you that the `sms` param is `+0000000` and the `body` params is `Hello`

When clicking on one of the apple formatted ones, the android system doesn't understand it properly and just reports to the app that the `sms` is `+0000000&body=Hello`. So, it should just be a matter of detecting the `&` character in the `sms` field and knowing to split it up and parse the message body manually

**Comment by Roy-Orbison** [comment]
You could run it through a normal URL query parser in that case, then use only the (last) `body` parameter if it exists.

**Comment by moezbhatti** [comment]
Fixed in 3d4899cb059b82cd04259d6d9f7bcf29619dddbb
