### ISSUE TITLE
[Feature Request] Show SMS mass messages as one in conversation list

### ISSUE THREAD

**Issue by jack1142** [moezbhatti/qksms#1369]
### DESCRIPTION
When I send SMS mass message (e.g. untick "Send as group message"), it's divided into separate conversation for each member of group I'm sending it to.

### EXPECTED
I expect SMS mass messages to stay grouped in conversation list, like it happens in Google Messages or Textra SMS for example. Replies of course would appear in individual conversations, but the message would be showed as one.

**Comment by moezbhatti** [comment]
Group messages will appear in a single conversation, but I don't think it makes sense for a mass-text to appear in one conversation. If you think about it, a group text is essentially just a lot of individual texts - they don't have anything to do with each other except that they were sent at the same time

And since replies will come in the individual conversation, I think it makes more sense to have the mass message appear in the individual conversation, so the reply has context
