### ISSUE TITLE
QKSMS+ payment identification in new or reinstallation

### ISSUE THREAD

**Issue by edmundlaugasson** [moezbhatti/qksms#1446]
### DESCRIPTION
Paid for QKSMS+: how is my payment identified on next installation? E.g. if I change phone or have multiple phones - how can I use QKSMS+ in next phone? It might also happen that I change the operating system of current phone, e.g. replace stock Android with LineageOS, /e/, Replicant, etc. and would like to install QKSMS+ again. I assume that this is one-time payment. Besides - Google Pay does not show that I have paid but I see from my account that I have paid and also QKSMS+ features are working.

### STEPS
1. pay for QKSMS+
2. (re)install QKSMS+ on phone, possibly also on next/another one
3. try to get QKSMS+ turned on
4. no information about that

### EXPECTED
During payment would expect kind of identity code to be generated or similar way to uniquely identify the paid user. Also a confirmation code via SMS would be enough. This could be also connected with Google Play user. But I might use also F-Droid or any other app store - what about then? How can I identify myself?
Would also expect that when such identification will be implemented then also all current QKSMS+ paid users will be identified as backward compatibility.

### OBSERVATIONS
After payment just gratitude but no information about securing my identity and allowing it to use in another phone.

Actually noticed a strange SMS after QKSMS+ installation which started with three characters, then colon and then 33 characters (letters, numbers) - all in capital. The sender was 4-digit number, completely unknown for me. Is this the SMS that is used for QKSMS+ identification? This could be also one solution, which would cost nothing. The issue would be that if backup feature is for paid users only then in such case the user cannot import SMS (including the identifying one) unless to allow still import in case of when the backup contains identification SMS - will be detected by app automatically before starting the actual import.

Using QKSMS v3.6.4
Android 8.0.0 (stock image with all current updates on Oneplus 3)

**Comment by moezbhatti** [comment]
Hey @edmundlaugasson, you raise some good points here. A couple things to mention

1. Your purchase is going to be linked to your Google Play account, and it is indeed a one-time purchase. As long as you're signed into the same account on Google Play on your other device, then you'll have access to QKSMS+. It's possible that you paid with a credit card instead of Google Pay, so there's no way to guarantee that the order will be there. It should be visible here though: https://play.google.com/store/account/orderhistory
2. If you're downloading the app on a device that doesn't have Google Play services, then presumably you're downloading it via F-Droid. In this case, QKSMS+ is automatically unlocked for all F-Droid users, so you shouldn't run into any issues there

I'm not sure what that message was, but it definitely didn't come from QKSMS. QK doesn't invoke any messages to appear ever, anything you see came from the outside world

Let me know if you have any other questions and I'd be happy to help!

**Comment by edmundlaugasson** [comment]
Thanks for clarification. Still if I currently used Google Play and possibly later F-Droid (e.g. decide to abandon the Google) then how would my identity transfer to F-Droid? There might be also other app stores used (e.g. Aptoide, etc. - https://alternativeto.net/software/android-market/). Will see then if you say that should not be any issues but currently still depending on Google :(
Now I see also last activity in Google Play and I see that payment.

**Comment by moezbhatti** [comment]
`QKSMS+ is automatically unlocked for all F-Droid users` :)

**Comment by gkeegan** [comment]
You would not need to worry about anything transferring to fdroid. With fdroid you automatically get QKSMS+. 

And there is no reason to use Aptoide when Fdroid is much better.

**Comment by gkeegan** [comment]
@moezbhatti seems like I should've refreshed the page before I commented :)
