### ISSUE TITLE
Larger-size auto-compression settings cause MMS sending to fail.

### ISSUE THREAD

**Issue by e-t-l** [moezbhatti/qksms#1510]
### DESCRIPTION
MMS containing images fail to send if auto-compression is set to 2000 KB or No Compression.

### STEPS
1. Go into the in-app settings.
2. Go to the auto-compression settings. 
3. Set to either 2000 KB or No Compression.
4. Attempt to send an image via MMS.

### EXPECTED
The text should send, and the recipient should receive the texted image.

### OBSERVATIONS
The MMS fails to send. An error message appears underneath it in the conversation view reading, "Failed to send. Tap to try again." Tapping this message fails to re-send the message. Even after changing auto-compression settings back to 1000 KB or smaller, tapping to re-send failed messages does not successfully send it.

**Comment by moezbhatti** [comment]
This isn't entirely unexpected. Most carriers have a limit of 1000KB, and so 2000KB just won't work for most people. That being said, the compression in QK isn't great and will often go a few KB over the selected limit, so you'll need to use 600KB in order to be safe on a carrier where the limit is 1000KB

**Comment by e-t-l** [comment]
Thanks, makes sense!
