### ISSUE TITLE
MMS don't seem to get sent

### ISSUE THREAD

**Issue by HackaN** [moezbhatti/qksms#1528]
### DESCRIPTION
MMS don't get sent (works in other apps such as Google Messages). Using version 3.7.6 from F-Droid on LineageOS 16/Android 9.

**Comment by moezbhatti** [comment]
Are they getting stuck sending, or do they appear to have sent?

**Comment by HackaN** [comment]
They appear to have been sent (although they have never had any delivery report status). No indication of any failure, until people start asking where the message is.

**Comment by RocketFox85** [comment]
Same issue here. v3.7.6 from F-Droid. Pixel 2 XL on Android 10. Message appears to have sent. Sometime recipients get them as group text. Other times *some* recipients receive the SMS as individual texts while others don't receive it at all. Switching to Google Messages seems to resolve the issue, which lead to me to search for similar issues related to QKSMS, and...here I am. Happy to provide any other info that might help.

**Comment by droopy4096** [comment]
3.7.6 messages get stuck in "sending" state intermittently. 3.7.4 downgrade fixed the issue

**Comment by jalba69** [comment]
Hello, 

having issues with MMS here too, trying to send pictures seems to fail each times.
The message is not sent for me and i have the line at the bottom notifying me and asking if i want to send it again, trying many times to send it again doesn't work.

- Tried to set the compression to lowest possible 100ko then 200,300 etc > no luck
- Removed the second sim card to test but no luck.
- Can't revert to a previous version like the poster above ( F-droid store tries to install 3.7.4 then i get a message saying it was not possible for some reasons, tried also the 3.7.9 latest apk and it also fails to install... ). Never tried to downgrade using F-droid so i don't know what is going on here.

The only thing a bit strange i notice is that on the failed message if i go see the infos using the ! symbol after selecting the message i see ( i translate from my French version )  : 

Message details 
Type : MMS
From : **insert_adress_token**
To : 00 00 00 00 00  (< a valid number)
Sent : 28/11/2019  15:27:36

I'm not sure if the **insert_adress_token** is normal or not in this case so here i am trying to bring another tiny stone to the edifice.

Sending text works just fine, sending even a tiny picture fails every-time it seems :/

Thanks a lot.

**Comment by moezbhatti** [comment]
Thank you for the details!

@jalba69 if you scroll up to an MMS that was sent before this bug appeared, what does it show in the `from` address?

**Comment by jalba69** [comment]
Hi,
on a old successfully sent MMS i have this for infos about the message : 

Message details
Type : MMS
To : 00 00 00 00 00 (< a valid number)
Sent : 3/4/2019 13:49:13

The "from" line is not present at all there.

Note that i rarely send MMS and the previous message having an image included is quite old so i don't know since when this MMS sending problem is there.

I'm receiving MMS images from times to times tho, however before updating to the new version of Qksms ( some months ago https://github.com/moezbhatti/qksms/issues/1460 ) i had the old version where if i make no errors in the options you had one for sending multiple sms as a mms and this was active and used often without issues.

Thank you.

**Comment by HackaN** [comment]
> Thank you for the details!
> 
> @jalba69 if you scroll up to an MMS that was sent before this bug appeared, what does it show in the `from` address?

I can confirm that it says "insert-address-token" in previously successfully sent mms:es.

**Comment by moezbhatti** [comment]
I've narrowed the issue down a little bit, but I'm having trouble figuring out the exact cause, as the issue doesn't seem to be happening on my own device. Would someone mind testing out a few builds for me? This should help me figure out exactly the source of the problem

You'll need to uninstall your existing version of QKSMS first

Then install the first test apk [here](https://drive.google.com/drive/folders/11n0Is1GdYtDba2XGFd8FGNX8Ht4ZqIyq?usp=sharing)

After installing it, send an MMS. In this first test, it should be able to send without issue

After that, install each successive APK, testing each one. Once it you install a version and the MMS is no longer sent properly, then let me know which version that happened on and I should know exactly what broke it

**Comment by HackaN** [comment]
> I've narrowed the issue down a little bit, but I'm having trouble figuring out the exact cause, as the issue doesn't seem to be happening on my own device. Would someone mind testing out a few builds for me? This should help me figure out exactly the source of the problem
> 
> You'll need to uninstall your existing version of QKSMS first
> 
> Then install the first test apk [here](https://drive.google.com/drive/folders/11n0Is1GdYtDba2XGFd8FGNX8Ht4ZqIyq?usp=sharing)
> 
> After installing it, send an MMS. In this first test, it should be able to send without issue
> 
> After that, install each successive APK, testing each one. Once it you install a version and the MMS is no longer sent properly, then let me know which version that happened on and I should know exactly what broke it

That worked like a charm for me. Tried two MMS:es, both got sent and delivered using the test-1.apk

**Comment by moezbhatti** [comment]
Sorry, I should have clarified. All of the APKs there are older builds, and essentially I'm trying to figure out exactly where it _stopped_ working, so then I can understand the changes that caused it.

Can you try 2, 3, 4, 5 and let me know which one breaks the MMS sending for you?

**Comment by HackaN** [comment]
> Sorry, I should have clarified. All of the APKs there are older builds, and essentially I'm trying to figure out exactly where it _stopped_ working, so then I can understand the changes that caused it.
> 
> Can you try 2, 3, 4, 5 and let me know which one breaks the MMS sending for you?

Yeah I noticed that after posting the comment, haha - I have now tried all five test.apks and I could successfully send MMSs with all of them.

**Comment by moezbhatti** [comment]
Oh, interesting. Are you able to confirm that each of them was also received by the recipient?

**Comment by jalba69** [comment]
Currently testing, need a bit of time but will post in a bit the final result, so far test1 and 2 apk worked

**Comment by jalba69** [comment]
1 > ok
2 > ok
3 > ok
4 > ok
5 > ok

So all worked for me too o_O Not sure it will help you pin point the problem :p
My version having issues if the latest one available on F-droid, so the 3.7.6

**Comment by moezbhatti** [comment]
Hmm, interesting. Can you try 3.7.5 and see if it's broken there? https://github.com/moezbhatti/qksms/releases/tag/v3.7.5

**Comment by jalba69** [comment]
3.7.5 seems to work too 

While i was at it i tested the 3.7.6 from github releases and it works too 

I don't understand what is going on here ¯\_(ツ)_/¯

Now i'll go try last f-droid released one again... Starting to wonder if something is wrong with an update process or maybe it is the settings inside Qksms, as all tested are stock settings.

**Comment by moezbhatti** [comment]
Oh, hmm.. very strange. Does 3.7.9 work too?

**Comment by HackaN** [comment]
> Oh, interesting. Are you able to confirm that each of them was successfully received by the recipient?

Yes, sent them to another phone which I was holding in my other hand

**Comment by jalba69** [comment]
F-droid 3.7.6 works now o_O

3.7.9 works...
I am lost now, i don't understand ...

The only difference i notice is after selecting a picture the small thumbnail in the message field is displayed blank compared to before( same on all versions tested) , previously i had a real thumbnail sowing a miniature of the selected image, now it's only a white square apparently, not sure if it is a real problem or not, might need to restart my device or something.

**Comment by jalba69** [comment]
In 3.7.9 I triggered again the same error after setting limit size to 1000ko, set it to 600 and it failed again, set it to default 300ko and it worked.

Now i need to try again the 3.7.6 from f-droid and try to change the size setting, i suspect it does not applied when trying other higher sizes some times ago, probably after setting it too high once and maybe the setting not applied when i set it back to lower sizes. I tried all size for invoices when having the issue. Just a guess but i will try it.

**Comment by jalba69** [comment]
Ok so 3.7.6 from F-droid, stock installation, sending pics work.

- Stock settings > works
- Set size to unlimited > fails
- Set size to 2000ko > fails
-Set size to 1000ko > fails
-Set size to 600ko > fails 
- Set size to 300ko > fails
- Set size to 200ko > fails
- Set size to 100ko > Fails

- Removed Qkms
- Install again from F-droid
- Stock settings > fails

- Removed Qksms
- Install 3.7.9
- stock settings > fails....

Well i have no words... Will need to try all process again tomorrow, with test 1 to 5 apk's and so on...
Something triggered the problem again and is probably locking something, restarted the phone but no luck so far :/ 

Will test more tomorrow and I'll report back, crossing fingers to get it fixed like the first time.

**Comment by moezbhatti** [comment]
Thanks, I really appreciate all the detail here. Are you testing with the same photo each time?

**Comment by jalba69** [comment]
I test with 2 or 3 pictures each time, always the same ones.

**Comment by moezbhatti** [comment]
I wonder if the behaviour is any different when sending group messages without an attachment, since they should be completely unaffected by the compression setting

**Comment by jalba69** [comment]
Never used the group messages so i can't say, not sure if i can test this.

So far after previous tests : tested to send a totally different pic just in case > failed
- installed test1 apk > works again , yeah :) 

-removed it and went to f-droid with 3.7.6 > stock settings working
-set size to 1000ko > fails
-delete failed message invoice from the list
-set size to 300ko > works.

Only thing different this time is i didn't launch the app from the F-droid store like it is possible to do from there and often did ( But closing the f-droid app after that ) 

After that i will try tomorrow to test this a bit more when i'll have time to kill.

For now the more i try the less clear i see :p 

Thanks a lot.

**Comment by HackaN** [comment]
That there's something buggy with the compression setting might be spot on. I have previously noticed (this might be a completely different issue and if so I , or someone, could open a new issue for that) that when sending a batch of images the resolution of those images are super-low when they arrive to the recepient. As if the compression setting gets set for the batch and not the individual items. Could be connected maybe. Or should this be a new issue?

**Comment by moezbhatti** [comment]
The compression limit is indeed for the entire batch. Unfortunately this is just the way that the carrier's set up their MMS limits - the limit applies to the entire message and not to each attachment

**Comment by HackaN** [comment]
Ah. Well now I learned something new 😁

**Comment by droopy4096** [comment]
trouble is in my case this is not limited to MMS - any text message has a good chance of being stuck in "sending"

**Comment by jalba69** [comment]
Hi all,

Testing a bit more this morning and not really more advanced than yesterday, problem seems to trigger quite randomly now, also had a strange thing occurring when i inserted my 2nd sim card again, it was not detected by qksms, no icon at the bottom to select card 1 or 2, scratched my head quite a bit with this one...

Main sim is from a French provider, other is from another country, so when in France it is in roaming mode, and it appears that both use the same provider when i'm here... So i tried to manually set the 2nd card to a different cellular network provider by going to the settings and assigning it a different French provider, just in case both providers having the same name was confusing qksms, but this made no difference.

But got it fixed in the end, i had the default phone sms app disabled since long time, enabling it again and setting it to be the default one before disabling it again worked, qksms shows the sim card icon again... 
This also fixed the small thumbnails for mms showing only a white square that appeared after testing the various versions yesterday, now i get the small thumbnails displaying properly again... Odd but ok, had this default sms app off since the first time i installed qksms, probably around 3 years ago...

Anyways, so far i cannot pin point what causes the problem with mms failing, it appears randomly on the 3.7.6 from F-droid and some newer builds. After installing the test1.apk version, then removing it and adding the f-droid one or others it works for a bit, then randomly start to throw errors after soem tests.

But now i think i found a way to unlock it without having to do the apps reinstall long process : 
- close Qksms ( seems important as trying without closing it seems to not work on the few tries i made ) 
- going to the app parameters > storage > clear cache 

and then i am able to click re-send the failed message and it works, I was never able to re-send a failed mms message before, once failed it was stuck for ever, no matter how many tries done, 
+ sending a couple of pictures after that worked too, then it starts to fail again after some tries but clear cache trick fixes it again. 

Not sure how the cache is supposed to work for this app or any other droid app, or if it's just some luck or something related to some of my specific phone mms issues, only thing i know is that now it seems i can fix the stuck mms refusing to be sent by cleaning the cache while qksms was previously closed, so it's a big plus already for me.

Biggest cache size i had to clean was 3.11mb, 
lowest i had to clean after getting message not sent was around 780Ko, 
pics i try to send come from phone hdd, it have around 15GB free space still,(did not tried to send anything from the additional storage SD 64GB card), and pretty sure the 3GB RAM is not used at max capacity with only qksms active and very few apps installed on my phone.

Not sure it will help to move forward with the issue but well...

**Comment by moezbhatti** [comment]
Hmm, I wonder if this issue might be dual-SIM related. Is anyone who is expeeriencing this issue using a single SIM phone?

**Comment by moezbhatti** [comment]
I've found the fix! Going to publish in the next few days

Here's a [test build](https://drive.google.com/file/d/1bRlIgrqN2YXMGxWdzJlaau5HfLkRyBVU/view?usp=sharing) in case anyone wants to try it out in the meantime
