### ISSUE TITLE
Different colors for SIM card

### ISSUE THREAD

**Issue by OmlineEditor** [moezbhatti/qksms#1557]
Now the colors of SIM cards are gray. Make it possible to color the SIM card color in the settings. If the cards are different colors it is easier and easier to navigate. in the message when an SMS arrives on different SIM card can also be used in color.
![color](https://user-images.githubusercontent.com/13348933/72261157-5cfd1080-3625-11ea-8004-8a489553c7db.jpg)

**Comment by moezbhatti** [comment]
I think this would make the screen feel a little too messy, and then there would also need some additional settings added, which I just don't think would be worth it here

**Comment by OmlineEditor** [comment]
the user will decide to use different colors or only gray ones. If you add settings to select over time you will be able to analyze what users like the most? multi-colored data is easier to perceive with the eyes than single-color data. colors can be made not very bright, faded so that there is no color noise. OK?

**Comment by moezbhatti** [comment]
I think it's important to be especially careful around what we add settings for - otherwise we risk the settings screen becoming really cluttered and difficult to navigate. I don't foresee this setting being used often enough to warrant taking up space on the settings screen. Of course there's no way to know for sure unless you try it, but as the developer of the app I need to use my own intuition sometimes.

If this feature becomes a more popular request, I'm open to changing my mind
