### ISSUE TITLE
Compose new message should only show contacts (not groups)

### ISSUE THREAD

**Issue by kathytu** [moezbhatti/qksms#1593]
### DESCRIPTION
When I compose a new message and search for a contact, all the groups that contact is in on my phone shows up as well, which takes up a large block of the screen (esp if it's a big group). If possible, would love to only see contacts, not groups.

### STEPS
1. Compose new message.
2. Search for name.
3. See every group that person is in.

### EXPECTED
When I compose a new message and search for a name, I only want to see contacts, not groups.

### OBSERVATIONS
I see all the groups that contact is in.

**Comment by moezbhatti** [comment]
I disagree, I think that groups should absolutely be shown there. This has been one of the most requested features for a long time

That being said, the current implementation occupies way too much screen real estate, and I've condensed it significantly for the next update

**Comment by 4L3XK** [comment]
@moezbhatti Groups should definitely be shown in there.
Still it should be possible to choose for example whether groups are shown or whether groups are shown at the top or at the bottom.
This issue regularly disturbs me and I am glad to find an issue in the git here.
My contact book has many contacts who are in several groups, which means it takes up to two seconds for results to show up and then I always have to scroll to the very bottom to find the single contact I want to message.
I've been switching back and forth from QKSMS and other SMS Apps, just because of that.
I would give it a thumbs up, if the choice was left to the user to adjust the settings according to their use case.
