### ISSUE TITLE
Feature request: auto delete duplicate messages

### ISSUE THREAD

**Issue by creatorofthesky** [moezbhatti/qksms#1597]
First of all I would love to say this is a wonderful application and I have been using it for some time. Keep up the good work!

My issue is not an issue with your application in the slightest. My phone or tower seems to be malfunctioning to the point where I get numerous duplicate texts.

It would be amazing if a feature could be added to detect them not display notifications of them and auto delete them. All optional in settings of course. With maybe a setting that determines how many past messages it checks.

Thank you for your time and have a wonderful day!

**Comment by Saijin-Naib** [comment]
I was just going to open a new FR for this feature.

At some point in the past, one of the tools I used for message backup/restore seems to have duplicated in-place a ton of my messages.

A means within QKSMS (or likely QKSMS+) to find and purge these duplicate records would be amazing!

**Comment by moezbhatti** [comment]
I think this would be pretty great for a standalone SMS utility app, but it might be too advanced/specialized to include in QKSMS. I might consider some sort of duplicate detection logic fore the restore-from-backup functionality, since it currently does not have that and might create duplicates, but that's a separate issue to what you're describing here
