### ISSUE TITLE
LED colour does not follow theme

### ISSUE THREAD

**Issue by sphh** [moezbhatti/qksms#1600]
### DESCRIPTION
I learned from #1035 that the LED colour should follow the theme (at least that's my understanding of @moezbhatti's comment https://github.com/moezbhatti/qksms/issues/1035#issuecomment-381308874). I believe, it does not on my phone.

### STEPS
1. Set the theme to yellow
2. Receive a message
3. The LED blinks purple

Or
1. Set the theme to green 
2. Receive a message
3. The LED blinks purple

### EXPECTED
I would expect the LED to blink in yellow (or green).

### OBSERVATIONS
The LED blinks in purple IMHO not honouring the main colour of the theme. Maybe I misunderstood https://github.com/moezbhatti/qksms/issues/1035#issuecomment-381308874 ... (On a side node, I would definitely prefer to be able to customize the LED colour)

**Comment by moezbhatti** [comment]
The LED is actually always [set to white](https://github.com/moezbhatti/qksms/blob/5512b344d67b1fd9e5921e7ba6d99b94e702a629/presentation/src/main/java/com/moez/QKSMS/common/util/NotificationManagerImpl.kt#L142), however on some phones the "white" isn't really white and that's why you're seeing it as sort of a purple

I don't plan to have it follow the theme, since lots of the colours may have poor visibility and I think that I'd be overcomplicating things if I tried to figure out which ones were ok and which ones were not. Instead, any customization will just be manual. So I'll close this issue in favour of #1035

**Comment by sphh** [comment]
Well, I prefer to be able to customize the LED colour, so I am looking forward to seeing it (re)implemented. Thanks!
