### ISSUE TITLE
Archive single messages for package lockers, confirm your phone number, and other messages from noreply correspondents.

### ISSUE THREAD

**Issue by jtagcat** [moezbhatti/qksms#1619]
Any package I get, I get an sms 'you have package, use code 123456 to get the package'. It's quite hard to keep track of what I have. Most delete the messages, but as I see it, messages should not be deleted.

It's also quite annoying to have postal bots and confirm-your-phone-number bots mixed with humans, every 2nd thread in the home screen is 'CODE IS 10932120938123', 'THANK YOU FOR USING', 'DO NOT SHARE WITH ANYONE'.

I think this feature requests includes 2 (possible solutions):
 - Separate no-reply sms from human sms (and 3rd section, sms from contacts?), with manual override per-message-thread.
 - Archive/Manually acknowledge a single message. I'd be fine with hold to select, then select archive, but a nice touch would be slide-to-archive.

**Comment by moezbhatti** [comment]
I don't currently have plans to separate the inbox (or do any sort of detection for the sender type), but slide-to-archive is already possible and enabled by default!

**Comment by jtagcat** [comment]
Not separate inboxes. Archiving (single) messages within a conversation. Everyone, including me delete older messages, to keep up with what packages have been received.

I know it might be foreign, but instead of going to the post office, or delivering to your door, we have package lockers nearby grocery stores etc. For example, all my AliExpress packages get delivered there (there're advantages and disadvantages, but I'm not going to get in to the way the world works).

After a package has arrived, you get an SMS. It contains:
 - the tracking number of the package
 - date of expiry (you better get your package before this date (on some providers date+1d) )
 - the pin (lenght depends on provider) to open the locker; this can be shared with another person (giving them the permission to unlock the locker)
 - Bunch of noise text.

Here's an example from Omniva (the funded-by-government national private courier, it's more messy, not going to get in to that):

![image](https://user-images.githubusercontent.com/38327267/103450929-4d069280-4cb5-11eb-83fd-153eae9aed17.png)

1. Reminder: Your Package {trackingnr} with date of expiry 11.12.20 (2020-12-11) has arrived {location of locker} package machine/robot/locker. Doorcode is 863674. Please come take your package asap. Your Omniva.
2. (and 3.) Hi, a package has arrived to Omniva's {location of locker} package locker package {trackingnr}. Doorcode {doorcode] Date of expiry 15.12.2020. Your Omniva.
4. Dear client, {trackingnr} to {location of locker} has arrived. Your doorcode is 015333. Come take your package within 4h and win: omniva.ee/4h. Your Omniva.

There're like 30 messages in the conversation. What if you already used codes from message 1, 2, 3, 5, 6; but not from 4, 7, 8? You either have to make notes elsewhere (inconvenient, error-prone, etc) or delete the messages (also error-prone to deletion, and archival is preferred over deletion). Pretty much everyone deletes the messages.

This issue is to request archival of _single messages_ within the conversation (not the whole conversation).

Sliding a message to the right/left should archive that message. Holding/selecting multiple, and then archiving should also be an option.
I'd recommend being cautious of future possibilities with rich text messages, namely replies (see telegram's implementation); but the sliding behaviour, can be later modified by the user, if more options pop up.

**Comment by moezbhatti** [comment]
Hey @jtagcat, thanks for clarifying! I see what you mean now.

I'm not sure if there's really a good solution to this. Once you add the ability to archive specific messages, you need to figure out how/when to show them again

With conversations it's easy. It's whenever there's a new message in that conversation

With messages, it probably requires some manual user intervention. Which could lead to some problems if people accidentally archive something and then don't know what happened or where to find that message - which is a reasonable thing to assume since I don't think this kind of functionality really exists in any other messaging app

You could guard against that by adding a setting to enable/disable this functionality, but then I think we're getting way too deep for something that likely won't be useful for that many people

Because this is such a specific usecase, I feel like the best way to deal with it is to set up a task with Tasker to take the incoming messages from this address and then add them to some sort of to-do list, where you can check off the entry for each message one by one
