### ISSUE TITLE
Dual Sim support

### ISSUE THREAD

**Issue by hoseinit** [moezbhatti/qksms#207]
Is it possible to add Dual sim support?
when sending sms asks us to send with which sim or have 2 buttons for sending via sim 1 or sim 2

**Comment by lfom** [comment]
At least display where the message came from, either SIM1 or SIM2. Most phones with dual SIM support changing the SIM used to send messages either by the notification bar or a dedicated button so if the app displays the SIM in the convos I think it's almost perfect. ;)

**Comment by djibux** [comment]
I would love dual sim support as well.

**Comment by geocine** [comment]
this would be a great addition

**Comment by alexisju** [comment]
:+1:

**Comment by scherom** [comment]
I am also using a dual sim phone and would love to see the dual sim capability for that otherwise great app. For me dual sim is : showing with the text to what sim a message was sent and being able to use the "chose before" each sending the sim card.
Thank you so much.. willing to give feedback when there is a testversion available.

**Comment by sarfraznawaz2005** [comment]
+1

**Comment by equaeghe** [comment]
Some things that may be useful to keep in mind (although focus on the pure dual-sim case deserves priority IMHO):

Note that there exist triple-sim phones as well. So multi-sim support would perhaps be a better title of this issue, although special attention to the dual-sim case may be appropriate, as it is so common.

Also SIP connections can in principle also send and receive messages, although support for that from voip providers (and perhaps the underlying Android stack) is still typically lacking. I have a dual sim phone with two additional SIP connections and when dialling, I get a pop-up menu offering me the choice of sim1, sim2, sip1, and sip2, so it may be that the underlying stack treats sims and sips similarly.

**Comment by israel-lugo** [comment]
Just wanted to leave my interest as well, even though from what I gather, the author @moezbhatti doesn't own a dual SIM phone to test this on.

I installed QKSMS today out of curiosity, and already I am amazed. The sheer volume of configuration possibilities is excellent, and the app is beautiful. Much better than the stock app.

Unfortunately, I switch between SIMs a lot, one for a certain set of people and the other for the rest, so the inability to choose when sending (and, to a lesser extent, to see which SIM received the SMS) is a show stopper for me.

Perhaps we all need to pitch in and buy @moezbhatti a dual SIM phone ;-)

**Comment by ciper** [comment]
Or offer beta builds dual sim support so those of us with dual sim phones can test it

**Comment by azzamsa** [comment]
I would love dual sim support as well.
this is the only feature I wait :)

**Comment by fungs** [comment]
Most wanted feature!

**Comment by eehpcm** [comment]
I hate to go all AOL on you, but...

**Me too!**

At a minumum, it should ask which SIM to use before sending.

Next level up, has a setting for "always SIM 1, always SIM 2, always ask."  Of course, if you set "always SIM 2" and there's no signal then QKSMS should offer the option of using SIM 1 or retrying on SIM 2.

Next level up, if you're replying to a message that came in on SIM 2 then the "always ask" shows both SIMs with SIM 2 preselected; if the message came in on SIM 1 then SIM 1 is preselected.

**Comment by fungs** [comment]
Well, default sim for messages is set in newer Android versions. An ask feature would be most important and (I suppose) simple to implement. The  way others (ChompSMS) do it is to remember a default sim per chat/contact and show this as a number on the send arrow.

**Comment by lfom** [comment]
Simply showing in the message if it is related to SIM1 or SIM2 would be enough IMO. How we reply can be managed by ROM. Thanks.

**Comment by lfom** [comment]
Show the SIM number in Received messages, just to make it clear.

**Comment by MathieuDenat** [comment]
Hi,
I need this issue too.
It will be a great feature on Android lolilop using on crosscall trekker M1.

**Comment by eehpcm** [comment]
Clever algorithms to determine which SIM to use are OK, but they'll _never_ match my requirements exactly.  Because the way I use things means that I cannot assign a particular SIM to a particular contact on a permanent basis.  One SIM has 200 minutes/month, but few of my contacts know I have that number.  The other SIM is PAYG and most of my contacts know about it.  So which one I reply with depends on a number of changing factors.

To that extent, I don't really care what algorithm is used to guess which SIM to use as long as I can easily and quickly over-ride it.  My preference is that the phone presents me with the choice of both SIMs and its algorithm has pre-selected one of them but I get to decide.  If I'm lucky, the phone guesses right and I just have to touch send; if I'm unlucky I have to select the other SIM before pressing send.  For me, that final over-ride is vital.

**Comment by BennyBeat** [comment]
+1!
I love QKSMS and all the gazillion available options but, unfortunately, I'm stuck on Android's default SMS app because I can't choose with which SIM sends an SMS. Hope this can be solved ASAP... Cheers!

**Comment by gkomarnicki** [comment]
Dual SIM capabilities will be a much-needed feature for us in the Philippines, as just about all Android phones sold here are dual SIM. Many people buy their device unlocked, and going prepaid is a lot more popular since they can switch networks anytime they wish.

Filipinos use two or more SIMs to take advantage of the best plans and promos each carrier has to offer. Plus the cellular reception of one carrier may be poor in a certain area, while the other carrier’s signal may be much better.

Multiple SIM support was introduced in Android 5.1, so hopefully this could eventually be implemented in QKSMS.

**Comment by pras92** [comment]
It's bad that QKSMS still doesn't support dual SIM. 

Someone pointed that just a mention of SIM # is enough, as choice of SIM can be handled by ROM.
However, there are times when we'd like to reply from the SIM that received an SMS, rather than the default SIM as set by ROM. 
So, both the SIM # and an option to choose SIM while typing each SMS is what will fulfill the dual DIM support feature. Just like how MIUI stock messaging app handles.

**Comment by MyNameIsCosmo** [comment]
Dual Sim is planned after the initial release of QKSMS3.

I'm sure Moez will gladly review any pull requests adding in support for dual SIM.

**Comment by moezbhatti** [comment]
Implemented in version 3.3 :)

**Comment by azzamsa** [comment]
After a long wait. Thank you for your contribution to community Moezbhatti.

**Comment by eehpcm** [comment]
Thanks for that.

I suggest you check what happens if you swap the SIMs.  Some apps get this right, some apps mistakenly think that the SIMs haven't been swapped and misidentify them.  I suspect there are two APIs involved and one of them doesn't quite do what the app author thinks it does.

**Comment by moezbhatti** [comment]
@eehpcm the app will respond to SIM changes in realtime, and can switch in and out of dual sim mode while the app is running

**Comment by eehpcm** [comment]
@moezbhatti 
> the app will respond to SIM changes in realtime,

I can't do that on my phone.  To physically swap the SIMs I first have to remove the battery.

I had to do this because the VoLTE app from my MNO said it couldn't connect to their network.  The SIM for that MNO was in slot 2.  Their support suggested swapping it to SIM 1.  It didn't fix the problem.  And although Android itself recognized the change, some apps did not and insisted that the
SIMs for the MNOs were still in the slots they were originally and not the slots where they were currently.  I'd be unhappy if QKSMS got that wrong and instead of sending using the SIM where I have unlimited texts it used the one where texts cost me money whilst telling me it was using the SIM with unlimited texts.

That was back on Android 6.  With Android 7 the VoLTE app could connect.  ISTR I had to do something like disable one of the SIMs and re-enable it before everything finally recognized the swap.

> and can switch in and out of dual sim mode while the app is running

What do you mean by that?

**Comment by LeedsCode** [comment]
I see the option now for switching the sim in individual messages; however, the app doesn't seem to default to the preferred sim card. In my settings on Android I have 2 SIMs for `Calls & SMS` where the 2nd SIM is preferred. When in the QKSMS app it always seems to default to using the 1st SIM card - those conversations already existed in fact, using the 2nd SIM card (which was my only SIM card before).

Would it be possible to default to the preferred, or at least have an option in the settings to select the default SIM card to use?
