### ISSUE TITLE
Suggestion : Static but expandable current conversations

### ISSUE THREAD

**Issue by MostHated** [moezbhatti/qksms#266]
Really like the app, but one thing I would like to suggest be implemented would be that the expandable message sidebar have an option to always be visible in a minimized way similar to Hello SMS and Evolve SMS but can easily be swiped to expand, and also add perhaps a little number as a notification icon on each message to show how many new messages each one has and for those with no pic, just use the contacts initials, or the last few numbers in their phone number or something?. Here is a shitty photoshop I whipped together to demonstrate (I didnt optimize the space usage on the left of the contact icons or anything obviously) If you were able to do this, I would definitely use and recommend it to anyone looking for a good text app. : )"
Thanks!

http://i.imgur.com/0xdlUck.jpg

![ss 2015-11-05 at 09 02 49](https://cloud.githubusercontent.com/assets/3442753/10983257/7f6a549a-83df-11e5-98dc-cac4904466a3.jpg)

**Comment by The0x539** [comment]
Hey, I literally just opened up GitHub to suggest this. Going with existing QK jargon, it's like a "reverse sliding panel tab. Instead of the list view having a bit of the conversation, which can be expanded to show the conversation full screen, the conversarion view has a bit of the list, which can be either expanded or used while semi-collapsed.

Not only would I actually use something like this instead of the partial-conversation panel (I'm made a bit uncomfortable when an app has no "neutral home view" where no subsection is favored over the other), but I daresay it's more useful. While this lets you switch between any of your onscreen conversations with a single tap instead of the 2taps or swipe+tap required before, the existing/current sliding panel tab lets you...accomplish with a tap or a swipe what could already be accomplished with a different tap, and maybe a little bit of scrolling?

**Comment by moezbhatti** [comment]
Interesting suggestion. Looks pretty nice

I don't plan on adding this to the app however. I don't think it agrees with the direction of the app's design language, in spite of looking fairly nice on its own
