### ISSUE TITLE
MMS image preview is same for all images

### ISSUE THREAD

**Issue by Atmanbay** [moezbhatti/qksms#31]
The preview shown for all images is the preview of the most recently received image. Clicking on the preview shows the correct image

**Comment by srcreigh** [comment]
This is the silliest bug! Neither moez nor I can reproduce it. @Atmanbay we'll need your (or someone else's) help to fix this bug and perform testing since we don't have the ability to repro on our own.

I can make a post on our G+ testing community about fixing this. We can try and get a bunch more people to help out so that it's not just one person.

**Comment by mperez19** [comment]
@srcreigh I am also seeing this bug. How can I help you fix it?

**Comment by ebony76** [comment]
i have also had this bug from day 1. Even before being in the play store. Verizon S5

**Comment by srcreigh** [comment]
We picked up a Galaxy S3 the other day so we can test. Fix out soon!

**Comment by sloonark** [comment]
This happens for me too on a Galaxy S4.

**Comment by Mitheren** [comment]
This is still happening to me as well (Galaxy S6, v 1.10.0). If you still need help reproducing it I'd love to give you a hand.

**Comment by Samcfuchs** [comment]
Could not repro on Moto X 2013.

**Comment by moezbhatti** [comment]
Should be fixed in QKSMS 3.0
