### ISSUE TITLE
[Feature request] Notification sound/vibration for open conversation

### ISSUE THREAD

**Issue by szabolcsx** [moezbhatti/qksms#323]
I noticed that if a conversation is open and I get a new message it just pops up without any notification. This is okay if I constantly stare at my phone but usually I just put down while the screen is on and do something else so if I get a new message I simply don't notice. It would be nice to have some kind of notification for that, a sound or just vibration. Better selectable in the settings.

**Comment by moezbhatti** [comment]
Absolutely agree, I'm planning on this for the next update

**Comment by point-nine** [comment]
I like QKSMS, but have the same problem as the one described which makes it unusable for me.  I've noticed that 2 updates have been released since 12.29.2015 yet am unable to find any reference to
this bug.  Also, a change log would be a really handy, professional thing to make available.  If it exists, I would love to know where ...

Thanks

**Comment by moezbhatti** [comment]
This is fixed in QKSMS 3.0

**Comment by Dudule45** [comment]
Hello,
I used 3.8.1 on an old unconventional phone, and it vibrated when a conversation was open and a new message arrived but I changed my phone for a Oneplus 5t and installed 3.9.4 and it remained silent when I get a new message in a open conversation.
How and where can I modify the parameters ?

**Comment by Dudule45** [comment]
Any update ?
