### ISSUE TITLE
Wakelock Battery Drain

### ISSUE THREAD

**Issue by AnotherAndroid** [moezbhatti/qksms#344]
Hi there,

First off, love the app been using it for over a month without any issue.

Just recently, QKSMS has been preventing my phone from going into deep sleep. I must force close the app and then the CPU will go into deep sleep. I've tried clearing app cache, app data, uninstalling, and wiping the cache all to no avail. I've since switched to Textra (really don't want to) and its no longer happening.

If there's any more information I can provide, please let me know.

Oxygen OS 2.1.3x
OnePlus X

**Comment by pedro-araujo** [comment]
I am experiencing the same issue in my Nexus 5 with the latest nightly of CM13. What could be causing the issue?

**Comment by Primokorn** [comment]
I also have a Nexus 5 with a CM13 based rom and I have this wakelock:
MMS Connectivity (com.moez.QKSMS.QKSMS): 16 m 20 s  Count:0 98.8%
My device is unplugged since Since 16 m 32 s...
[BetterBatteryStats-2016-02-04_165949003.txt](https://github.com/qklabs/qksms/files/117744/BetterBatteryStats-2016-02-04_165949003.txt)

**Comment by moezbhatti** [comment]
Not really sure, the major battery drain that affected QKSMS users was solved a little while ago, and I haven't really received much detail about this one since then, so it's hard to know exactly what's causing it

**Comment by Primokorn** [comment]
@moezbhatti I uploaded a BBS dump file. What else do you need?

**Comment by moezbhatti** [comment]
This should no longer be happening in QKSMS 3.0
