### ISSUE TITLE
[Feature Request] Make the counter for Remaining Characters always visible during composing text!

### ISSUE THREAD

**Issue by therob84** [moezbhatti/qksms#386]
Now the remaining characters for a SMS is started to count down beginning with 10.

To fit a sentence in 1 SMS it does not help much to see only the counter appearing during the last allowed word.
I need to see it always when typing. This late appearence is not helpful in my opinion.

Display the counter always or make the limit customizable!

Thanks.

**Comment by sebalis** [comment]
I too would love to see the character count all the time. As a new Android user I was strongly irritated that I could not see a character counter for my SMS messages and that there was no information to find on the web about this. Having an option in QKSMS (which I installed in the hope to get a counter) would have made me understand sooner that a counter does exist. But even now that I have understood where the counter has gone I find myself missing it – I want to see early on how close I am getting towards my limit, not only when it is almost too late.

**Comment by moezbhatti** [comment]
For the sake of preventing the app from becoming cluttered, I'm going to decide against implementing this. I appreciate the suggestions however, please let me know if you've got any other suggestions for how the app could be improved

**Comment by JonnyTech** [comment]
If always displaying the count was made an option then users could decide for themselves if this useful feature was considered screen clutter or not. One cannot "fall in love texting" (quote from the app description) if requests are rejected purely from one person's (albeit the developer's) opinion. Please reconsider your decision.

**Comment by moezbhatti** [comment]
I certainly understand the sentiment, and that is why the app is open source, so that people have the freedom to modify it as they wish. I understand that not everybody is a developer, but there's only so much I can do

The problem with adding a setting for every single feature is that the settings screen becomes cluttered with things that most people don't care about, and it can grow infinitely large. Many people complained that the settings screen in QKSMS 2.x had too many options and was hard to navigate. I understand that this is in part a design issue, but nonetheless I need to carefully consider which settings I add, and I need to prioritize features that are going to be used by a larger percentage of the userbase
