### ISSUE TITLE
Show more lines when typing a message

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#394]
Would anyone be interested in having this? How many lines would you think are appropriate?

**Comment by therob84** [comment]
Maybe you mean this:
If I type a message in composing window at my 5" display (Android 5.1) a maximum of 8 text lines are displayed in vertical display alignment. In principle that's OK.

**BUT**: If I type more than 8 lines (equals 2 full sms) I cannot see anymore the end of the message while typing, so I have to type blind! 
That's not good.

The problem is:
- the compose window partly extends behind the keyboard
- the compose window don't have any scroll behaviour

If you mean this with your question, then: 
--> Not more lines are neccassary, but a scroll funtion inside the compose window!

**Comment by moezbhatti** [comment]
Scrolling is actually already possible, I think the person who originally requested this just wanted to be able to see more lines before it's cut off and you're forced to scroll

**Comment by therob84** [comment]
> Scrolling is actually already possible,
Scrolling works in the compose window, but for me it is not possible to scroll that much down to see also the last line (where the cursor is located). The keaboard-layer is instead in the foreground!

**Comment by bru09** [comment]
Maybe it is just because, when typing a new message, not in an existing conversation, the last line of the compose window is hidden behind the keyboard and not just above the keyboard. Scrolling to go to the end is not that easy.
It doesn't happen when typing a message in an existing conversation, because in this case the last line is always above the keyboard.
If the last line would stay above the keyboard also for a new conversation, I think this would be OK for this point.
