### ISSUE TITLE
Preference switches glitching

### ISSUE THREAD

**Issue by licaon-kter** [moezbhatti/qksms#426]
I guess it's this bug: https://code.google.com/p/android/issues/detail?id=26194

Props to @M66B for tracking [the issue](https://github.com/M66B/NetGuard/commit/4c0eb31e6cdadc4570a25c2c320048b491136dac) for his projects. 

I did a quick implementation of this for https://github.com/Neamar/KISS/pull/413

Here (I guess) it's in [QKSwitch](https://github.com/qklabs/qksms/blob/master/QKSMS/src/main/java/com/moez/QKSMS/ui/view/QKSwitch.java) but maybe it needs a proper dev that can implement this with `android.support.v7.widget.SwitchCompat` instead of `android.preference.SwitchPreference` the above projects use.

**Comment by moezbhatti** [comment]
Didn't seem to work for me. I need to set a custom switch view to support the custom colors, but it seems like SwitchPreference doesn't let you set a custom switch view. It doesn't show the state at all. Right now it works because I'm using CheckboxPreference

I'll try to mess around with it and make it work, but so far there's not much luck

**Comment by licaon-kter** [comment]
I'm only familiar with the way NetGuard implements it, and that has custom (albeit predefined) theme colours.

**Comment by moezbhatti** [comment]
This is fixed in QKSMS 3.0
