### ISSUE TITLE
MMS Behavior Option

### ISSUE THREAD

**Issue by W1nks** [moezbhatti/qksms#453]
### DESCRIPTION

I'm having issues sending/receiving MMS messages while connected to a VPN.  I used to think this was Wifi issue but after more troubleshooting it turns out it's the VPN.
### STEPS
1. Connect to VPN (such as OpenVPN)
2. Try to send/receive MMS
### EXPECTED

The message should be received/sent without issue.
### OBSERVATIONS

I think I may have found the solution to this problem.  I started trying many different texting apps while troubleshooting my MMS issue and ended up finding a setting in Textra called "MMS Behavior".  By default it's set to "Legacy" and under that it says "Try 'System' if legacy MMS isn't work (for example with Project Fi, VPNs, WiFi MMS, etc)."  So I then set it to "System" and it appears to have fixed the problem.  I have seen this option in other apps such as YAATA SMS and ChompSMS.
Is this something that could be added?  I'm not sure how difficult something like this would be to add because I'm not a programmer.  It seems like maybe it's just a switch saying use the system settings on the phone instead of the app settings.  Hopefully it's something simple and easy that can be added to this app!

For the time being I am just using Textra because I don't want to miss out on messages but I prefer QKSMS over any of the messaging apps I've tried! Even with all the different customizations on the other apps I still want to come back to this one :)

**Comment by InfinityDeltaX** [comment]
Based on [this](https://github.com/WhisperSystems/Signal-Android/issues/4131) I'd assume that the System option refers to using [this](http://developer.android.com/reference/android/telephony/SmsManager.html#sendMultimediaMessage(android.content.Context,%20android.net.Uri,%20java.lang.String,%20android.os.Bundle,%20android.app.PendingIntent)) API.

**Comment by protist** [comment]
I can confirm this bug. With VPN disabled, MMS works again. The stock Cyanogenmod SMS app works fine with VPN enabled. Unfortunately this is a deal-breaker for me too. ☹

**Comment by moezbhatti** [comment]
QKSMS 3.0 now uses these new APIs to deal with MMS. The issue should be resolved!

**Comment by firecat53** [comment]
On January 11, 2018 1:16:00 PM PST, Moez Bhatti <notifications@github.com> wrote:
>QKSMS 3.0 now uses these new APIs to deal with MMS. The issue should be
>resolved!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/moezbhatti/qksms/issues/453#issuecomment-357063758

Nice. Shouldn't you leave the issue open until MMS support is completely added so we can test it though? I see receive support is added but not sending MMS yet.

Scott

**Comment by moezbhatti** [comment]
@firecat53 you're right, it is a bit premature to close the issue now. I've been very liberal with closing issues in preparation of QKSMS 3.0, because last week there were around 350 issues open and honestly it was just a massive and unmanaged mess.

Almost all of them have been confirmed solved, but in certain cases like this I'm closing the issue prematurely because I don't expect there to be an issue, but I'm completely open to reopening it if it's confirmed to be not resolved.

I'll only be treating it in this backwards way this while I'm still in the process of trying to significantly cut down on the outdated issues, and then once 3.0 is stable I'll be taking a more sensical approach and not closing issues until they're confirmed to be solved.

If you'd prefer this issue stay open in the meantime, let me know and I'd be happy to leave it open

**Comment by protist** [comment]
FWIW this works fine for me with the latest version from F-Droid (3.5.4).
