### ISSUE TITLE
Error while looking at pass messages and receiving sms

### ISSUE THREAD

**Issue by bendsley** [moezbhatti/qksms#538]
### DESCRIPTION

If you are scrolling through past messages received through one conversation and receive a message for another conversation, the initial conversation you're scrolling through (history of messages) will scroll (very fast) to the very end of that conversation.
### STEPS

Conversation 1 and Coversation 2 (C1 and C2)
1.  Have at least two conversations going.
2.  Scroll up to look through past message history in C1.
3.  When C2 receives a message while looking through C1 history, C1 will scroll all the way to the bottom of message history (it did not receive a message)
### EXPECTED

C1 and C2 receive messages, but one does not adversely affect the other.
### OBSERVATIONS

When C2 receives a message while looking through C1 history, C1 will scroll all the way to the bottom of message history (it did not receive a message)

**Comment by sm4rk0** [comment]
Related to #272 and #332

**Comment by moezbhatti** [comment]
Thanks @sm4rk0 !

**Comment by Ketrel** [comment]
Additionally, I would like to suggest that an incoming message to C1 doesn't reset the scroll position in C1 either.  If you're scrolling back in an active conversion, as it stands right now, you'll be unable to get far because each incoming message to it resets the position.

In all honesty, I can't think of a scenario where the auto-scroll would be beneficial since to get to the bottom, you'd simply need to go back to the conversation list and then re-enter the conversation.

**Comment by sm4rk0** [comment]
This is fixed with #588

**Comment by moezbhatti** [comment]
This is fixed in QKSMS 3.0
