### ISSUE TITLE
Stage fright?

### ISSUE THREAD

**Issue by Orbyt** [moezbhatti/qksms#551]
When receiving videos, I get a message about stage fright. I understand this is an exploit in the stage fright lib, and has to do with automatic rendering of videos in messages. So what exactly should I do? Just not play any videos I receive? Can we detect whether the message contains the stage fright though?

**Comment by moezbhatti** [comment]
Yeah, if you want to avoid it for sure, then you'd need to avoid opening these on your phone. One possible way to view it would be to save it to your phone, and then copy it to your computer and delete it via your computer (rather than through your phone's file manager)

There may be ways to detect if a file is infected or not, but I don't personally know of any
