### ISSUE TITLE
Option to update QKSMS icon to theme color

### ISSUE THREAD

**Issue by z751** [moezbhatti/qksms#558]
This is a feature request.  

I do like the new design but I feel there is much more potential of it.  Is it at all possible to add an option to do this please?

Also I have noticed that on the dark icon it appears black on my home screen but in my app drawer it is a dark grey and is pretty hard to catch my attention to it.

Thanks.

**Comment by rugk** [comment]
I think actually this option was there in the previous version, but currently you can only choose between dark and light icon.

So please add the option back to update the icon with the theme color! This was such a pretty feature.

**Comment by moezbhatti** [comment]
So, the problem with that feature was that it required you to add a hardcoded image with that color applied to it into the app's assets. This is kind of alright when your app has a limited palette of themes, because you can just pick the icon that's most similar to the theme selected and just use that. And it'll probably be pretty close

But the problem now is that any RGB color is possible, so there's no way to have the app icon closely resemble the theme color, without manually adding hundreds or thousands of icons to the app

**Comment by z751** [comment]
Is it possible to have it create a new icon with the color on demand and habit make a new one when the option is selected?

**Comment by moezbhatti** [comment]
Unfortunately not, the colored icons have to be pre-packaged into the app

**Comment by z751** [comment]
So basically you do not have any plans to address this issue?

**Comment by moezbhatti** [comment]
Seeing as it's not possible to properly address, no. Unless I found a way to tint the icon programatically. But as far as I know, that can't be done

**Comment by rugk** [comment]
Why not just use the set of predefined colons it had before?
Personally I have nothing against it. You may display the predefined colours as the default selection and when the user switches to the colour palette and activates the option to colour the icon you may display a warning that another color has to be chosen or something similar.

**Comment by homersimpsons** [comment]
Or just a set for icon (red, green, blue, white, black)

**Comment by z751** [comment]
I also agree with @rugk

**Comment by moezbhatti** [comment]
Seems like a lot of people want this. I'll bring it back for the next update

**Comment by z751** [comment]
Thank you!

**Comment by moezbhatti** [comment]
Leaving issue open until it's completed

**Comment by z751** [comment]
Thanks for the fix bro!
