### ISSUE TITLE
Back buttons doesn't always go back to conversation list

### ISSUE THREAD

**Issue by fresheneesz** [moezbhatti/qksms#727]
### DESCRIPTION
When I press the built-in back button on my galaxy s5, it often goes to a different conversation rather than going back to the conversations list. I would imagine this is a bug, but if not, its not very intuitive behavior.

### STEPS
1. Go to a conversation
2. Press the built-in back button

It seems like conversations are being put into a queue and popped off when you press the back button, but the behavior isn't clear enough to me to find a consistent repro. 

### EXPECTED
Pressing the built-in back button should go back to the conversations list.

### OBSERVATIONS
It instead goes to some other conversation sometimes.

This is version 2.7.3

**Comment by cornercase** [comment]
I also experience this issue on version 2.7.3, both on stock Nougat on a Nexus 5X and an HTC One A9 Unlocked running Nougat.  It's inconsistent but I have had it happen many times on newly updated and cleared devices. Sometimes the back button goes from a coversation to the conversation list, other times it goes to the home screen, and other times it jumps to earlier conversations.  Clicking the app icon on the home screen usually jumps into a conversation rather than the conversation list.

**Comment by moezbhatti** [comment]
This is fixed in QKSMS 3.0
