### ISSUE TITLE
Sending messages via the camera doesn't work

### ISSUE THREAD

**Issue by srcreigh** [moezbhatti/qksms#75]
Hey Shane-

Thanks for the reply, I appreciate it. So here's what I've figured out:

-I can send pictures, as long as I used the camera app first to take the picture, by selecting the picture from my gallery through your app.
-If I try to take a picture through through your app, that's when I have the issue. It will take the picture but never send.
-I've tried with WiFi on and off for both scenarios and, at least for me, the WiFi status doesn't matter. 

So in the end, I can now use MMS. I just have to take my picture first using my camera app, then send it. I am able to receive pictures without any issues though.

Thank You,

--- <redacted name>

**Comment by ahattat** [comment]
I tried to reproduce the issue on Moto G 1st gen with Android 5.0.2, app version 1.12.1

1/ I got no problem sending a photo taken with the stock camera app.

2/ I got several issues with photos taken from within the app
   - photo is "incomplete" : mostly white with but a stripe of the actual picture on top (reproduced twice)
   - photo failing to load in the message writing area ("loading" is displayed for a second then disapears and nothing happens, reproduced 3 times)
   - photo is complete, loading correctly but fails to be sent (reproduced twice)

I couldn't get a photo taken from within the app sent correctly.

Hope this helps...

**Comment by Samcfuchs** [comment]
Couldn't reproduce on Moto X 2013.

**Comment by pille1842** [comment]
I've tested this with my Nexus 5. If I take a photo with the stock camera app and share it with QKSMS, I can send it without a problem. Same applies if I select the photo through QKSMS. However, if I take a photo from within QKSMS, it never gets sent.

**Comment by reppad** [comment]
I have the same behavior.
I think the problem is the size of the attachment.
When I select a photo from the gallery, the image is resized to fit the maximum size of an attachment configured in QKSMS (300k in my case).
When I took the photo from QKSMS, the picture weighs more than 1M (can be seen by viewing the details of the MMS in conversation), which results in the failure of the MMS sending (Orange, my mobile operator, limits the MMS size to 600k).

For information, photos taken via QKSMS (1 ~ 1.5M) do not respect the limits defined in parameters (300k) but they are smaller than the normal photos in the galery (4 ~ 5M).

**Comment by moezbhatti** [comment]
Awesome, thanks. I can confirm those steps work to reproduce the issue
