### ISSUE TITLE
vCard not supported

### ISSUE THREAD

**Issue by xavihernandez** [moezbhatti/qksms#763]
When someone sends me contact details as vCard I am unable to open. With AOSP Messaging app it's OK.

**Comment by jtsurf18** [comment]
@moezbhatti looks as though you added the feature label 4 days ago. Does that mean this is a consideration?

**Comment by moezbhatti** [comment]
@jtsurf18 correct, I do plan to implement this. Right now I'm focusing on preparing QKSMS 3.0 for a public release, this will likely come not too long after that

**Comment by jtsurf18** [comment]
@moezbhatti Roger that. Thank you


On Jan 16, 2018 at 4:28 PM, <Moez Bhatti <notifications@github.com>> wrote:

@jtsurf18 <https://github.com/jtsurf18> correct, I do plan to implement
this. Right now I'm focusing on preparing QKSMS 3.0 for a public release,
this will likely come not too long after that

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/moezbhatti/qksms/issues/763#issuecomment-358153889>,
or mute
the thread

**Comment by j0lk3n** [comment]
> @jtsurf18 correct, I do plan to implement this. Right now I'm focusing on preparing QKSMS 3.0 for a public release, this will likely come not too long after that

Any updates on this? I am using the free version and I still cannot open/import vCards
