### ISSUE TITLE
MMS Issues by Carrier

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#789]
Index for all carrier-related MMS issues

### AT&T
- #74
- #374 

### Project Fi
- #347

### Viettel
- #739

**Comment by janene001** [comment]
Do you have a comment thread for Sprint? We downloaded the qksms app for my son's phone because it was required by the Should I Answer app in order to block unwanted texts and calls. It's been working great to block creepy texts, but no matter how I update the settings, he can't send/receive any photos. He has a Sprint Moto E4. I've tried changing the MMS settings in qksms to unlimited file size, tried with and without Wi-Fi, made sure cellular data is on... Still won't send or receive MMS. I thought maybe it was a problem with Sprint, but when I change back to their default messaging app, he's got no problem sending or receiving photos. I did notice that if I watch real close there's a flash on his screen as soon as it would be receiving the photo I sent, but that's all. Am I doing something wrong, or is it the app? Please fix -- this is a wonderful app overall, and this mom is very happy that her son is no longer receiving those creepy unsolicited messages. Thank you!

**Comment by moezbhatti** [comment]
Going to close this as the existence of it is a bit confusing.

@janene001 in QKSMS 3.0 the MMS code is being completely re-written. The next update, or potentially the one after that, will include the ability to send MMS. Once that's out you can give me a shot and let me know if it works, if not, feel free to post a new issue!
