### ISSUE TITLE
Strip unicode

### ISSUE THREAD

**Issue by moezbhatti** [moezbhatti/qksms#815]
Add preference to strip accents to prevent SMS size limits from being reduced

**Comment by vivia** [comment]
Hi,

This feature didn't seem to work too well for Greek on version 3.0.4 (installed from F-Droid).

The killer feature, which made me switch to QKSMS, was the ability to automatically convert Greek Unicode into this subset that's inside the GSM alphabet if the message was too large. Note that this feature was a standard on all dumb phones, but in the smartphone era it's turned into a niche feature that's hard to find.

Anyway - I turned on the option to strip accented characters, but it failed to strip accented characters when the message was large enough. This would cost me money (because of sending more SMS than I intended to), so I had to pin it down to version 2.7.

**Comment by moezbhatti** [comment]
Are there certain characters which are stripped properly, and others that are not?

**Comment by vivia** [comment]
Sorry for the late reply - was too busy to test.

It seems to behave exactly the same as with the "Strip Accents" option turned off. That is, those letters that are already part of the GSM alphabet will work (capital Θ, Π, Σ, Δ, Φ, Γ, Ξ, Λ, Ψ, Ω), but none of the others.

**Comment by vivia** [comment]
Yes, the way I was testing was by writing the same character over and over and seeing how many characters it would let me input until it switched to the next message.
