### ISSUE TITLE
Memory Leak in ComposeActivity

### ISSUE THREAD

**Issue by reverse-unina** [moezbhatti/qksms#898]
I am using version 2.7.3 on both my real device with Android 7.1.1 and on my Android Virtual Devices.

When I change the orientation, i.e. rotating my device, multiple times I notice multiple instances of ComposeActivity in the heap memory and a growth of the heap memory usage. I noticed that it occasionally leads to an OutOfMemory error. If you cannot reproduce the failure, I could attach you the memory dump.

**Comment by moezbhatti** [comment]
This should be fixed in 3.0

I'm going to close this issue for now as I'm almost certain that it's gone (the entire app was completely re-written, this time which much closer attention paid to memory leaks), but if you find this to not be the case then let me know and I'll happily reopen and investigate
