### ISSUE TITLE
Some feedback from a daily user

### ISSUE THREAD

**Issue by Jatarii** [moezbhatti/qksms#956]
Hi moezbhatti

I'm using QKSMS 3.0 for a while now, and hereby I would like to write down my concerns, suggestions:

**Missing**:
- avatar in notifications: I really would like to see who send me a message in a glimp (I see this is already on the to-do-list)

**Suggestions**:
- please include the translations (I translated Dutch already)
- make the font inside the text-bubbles a little bit bigger, it's really small now
- Reconsider the colors in the dark theme. On my OnePlus 5t I can't see a difference between the dark background and the text-bubbles
- maybe some new icon so it looks more like the previous one (see below)
- On the conversationlist: maybe make the 'search'-bar like the themecolor? It looks so bright now
- don't show only emojis-messages inside a textbubble
- always show the timestamp of the latest message 

**Bugs**
- Color from avatar doesn't change to theme you set for that contact in the conversationlit (already reported)
- With the new QK reply: when you send a message with another app (Join) it doesn't show up in the QK reply window but it is visible in the app
- the automatic dark mode doesn't work on my OnePlus 5T

Hope it is some constructive feedback ;)

Many, many thanks for this app and that you listen to the community (something Pulse doesn't).

Kind regards
Jari
![logoqksms](https://user-images.githubusercontent.com/18144491/38188045-6aa39a28-365a-11e8-9f67-5b3ea87a5692.png)

**Comment by moezbhatti** [comment]
Going to split this up so that progress can be tackled one by one :)

- Notification avatars: https://github.com/moezbhatti/qksms/issues/860

- Translations: Added in 30506ce4a4b96f66c338424d3c221b5c72799215
- Font size: The app is using the font sizes described in the material design [documentation](https://material.io/guidelines/style/typography.html#typography-styles). That being said, I do plan on adding an option for larger text. https://github.com/moezbhatti/qksms/issues/953
- Dark theme: I don't have immediate plans to look into this, since the text is still very readable and it's less important that the bubbles are. When I have time to do a lot of testing with the colours I may explore some other options
- New icon: Oh, I really like this. I'll play around with it tonight
- Conversation list: I plan on keeping the toolbar white (or dark for the dark theme), to keep with the more minimal look of 3.0
- Emoji: https://github.com/moezbhatti/qksms/issues/286
- Timestamps: https://github.com/moezbhatti/qksms/issues/962
- Avatar color: https://github.com/moezbhatti/qksms/issues/954
- QK Reply: https://github.com/moezbhatti/qksms/issues/963
- Auto dark mode: Can you give me some more info? Does it just not work whatsoever?

**Comment by Jatarii** [comment]
just have a look at the time...
Also, sometimes the app doesn't switch to the dark theme, changing an option to the dark theme (eg: mode is on 'automatic', and select 'automatic' again, it changes)
![screenshot_20180403-074814](https://user-images.githubusercontent.com/18144491/38237529-c19e0426-3727-11e8-8338-462694b4e076.jpg)

**Comment by Jatarii** [comment]
I'll have a look how it works now. I saw you changed something with the latest beta.
