### ISSUE TITLE
Cannot receive MMS, maybe causing wakelock as well

### ISSUE THREAD

**Issue by bennaux** [moezbhatti/qksms#998]
I am using QKSMS 2.7.3 on Fairphone Open with XPrivacy and AFWall+ on a Fairphone 2.

The app cannot receive any MMS (sending only when enabling some foreign apps in AFWall+ and disabling WLAN, for some reason) and seems to create a wake lock as well, thus draining my battery very fast.

Is that a bug or did I do anything wrong?

Fairphone forum thread incoming MMS: 
https://forum.fairphone.com/t/qksms-and-incoming-mms/39178?u=hansibert

Fairphone forum post wakelock:
https://forum.fairphone.com/t/another-hot-fp2-with-empty-battery/39245/5?u=hansibert

**Comment by zawyer1** [comment]
Hello!

This is a well-known issue with the 2.7.3 version. I experienced the exact same issue. Whenever an MMS was sent to me, QKSMS would enable mobile internet, and then keep the phone in a perpetual state of "awake" -- but the MMS never came. The only way to prevent it was to re-install the app and completely turn off MMS on the phone.

If you try out the new 3.0 beta versions of QKSMS you'll notice that this bug is fixed.

**Comment by bennaux** [comment]
How can I get the new version? In FDROID and Google play, only old versions show up. Do I have to download the APK directly?

**Comment by zawyer1** [comment]
Yeah, APK here: https://github.com/moezbhatti/qksms/releases

It's still in beta, so some features are missing.

**Comment by bennaux** [comment]
I've installed 3.0.3, but it seems to not support MMS at all -- the messages I send do not arrive at the targets, and receiving does not work either. I cannot find the APN configuration in the app's settings any more as well.

**Comment by moezbhatti** [comment]
@bennaux what version of android is your phone running?

**Comment by moezbhatti** [comment]
Also, I'm going to close this as an issue is already up for the current version of the app. #945

**Comment by bennaux** [comment]
Okay, will answer your question there. :)
